"""
Functions for creating a multiple sequence alignment (MSA) using a similarity tree approach.
This module provides an alternative way to generate MSA by using hierarchical clustering
to build a guide tree, then performing progressive alignment along the tree.
"""

import numpy as np
import pandas as pd
from scipy.cluster.hierarchy import linkage, dendrogram
from scipy.spatial.distance import squareform

def build_similarity_tree(rmsd_df, method='average'):
    """
    Build a similarity tree from RMSD matrix using hierarchical clustering.
    
    Args:
        rmsd_df: DataFrame with RMSD values between all structure pairs
        method: Linkage method for hierarchical clustering 
                ('single', 'complete', 'average', 'weighted', 'centroid', 'median', 'ward')
                
    Returns:
        tuple: (linkage_matrix, ordered_structure_ids)
    """
    # Clean the RMSD matrix - replace NaN with max value and ensure zero diagonal
    rmsd_matrix = rmsd_df.values.copy()
    max_rmsd = np.nanmax(rmsd_matrix[np.isfinite(rmsd_matrix)])
    rmsd_matrix = np.nan_to_num(rmsd_matrix, nan=max_rmsd, posinf=max_rmsd, neginf=0.0)
    np.fill_diagonal(rmsd_matrix, 0.0)
    
    # Convert to condensed distance matrix
    try:
        condensed_matrix = squareform(rmsd_matrix, checks=False)
    except ValueError as e:
        print(f"Error creating condensed matrix: {e}")
        print("Ensuring matrix is symmetric and checking dimensions...")
        
        # Force matrix to be symmetric by averaging with its transpose
        rmsd_matrix = (rmsd_matrix + rmsd_matrix.T) / 2.0
        condensed_matrix = squareform(rmsd_matrix, checks=False)
    
    # Calculate linkage matrix using specified method
    Z = linkage(condensed_matrix, method=method)
    
    # Get the ordering of structures from the dendrogram
    dendro = dendrogram(Z, no_plot=True)
    ordered_indices = dendro['leaves']
    ordered_structure_ids = [rmsd_df.index[i] for i in ordered_indices]
    
    return Z, ordered_structure_ids

def create_guide_tree(Z, structure_ids):
    """
    Create a guide tree from linkage matrix Z.
    
    Args:
        Z: Linkage matrix from scipy.cluster.hierarchy.linkage
        structure_ids: List of structure IDs corresponding to the original data
        
    Returns:
        dict: Tree structure as nested dictionary
    """
    n = len(structure_ids)
    
    # Initialize tree nodes
    tree = {}
    for i, struct_id in enumerate(structure_ids):
        # Leaf nodes are original structures
        tree[i] = {'id': struct_id, 'children': [], 'is_leaf': True}
    
    # Build internal nodes from linkage matrix
    for i, (left, right, dist, size) in enumerate(Z):
        left = int(left)
        right = int(right)
        new_id = n + i
        
        # Create new internal node
        tree[new_id] = {
            'id': f"Node_{new_id}",
            'children': [left, right],
            'is_leaf': False,
            'distance': dist
        }
    
    # Root is the last created node
    root_id = n + len(Z) - 1
    return tree, root_id

def traverse_tree(tree, node_id, path=None):
    """
    Traverse the guide tree in pre-order, returning the visit path.
    
    Args:
        tree: Guide tree generated by create_guide_tree
        node_id: ID of current node
        path: Current traversal path (initialized as empty list)
        
    Returns:
        list: Traversal path as list of node IDs
    """
    if path is None:
        path = []
    
    node = tree[node_id]
    path.append(node_id)
    
    if not node['is_leaf']:
        for child_id in node['children']:
            traverse_tree(tree, child_id, path)
    
    return path

def create_alignment_order(Z, structure_ids):
    """
    Create an alignment order from the guide tree for progressive alignment.
    
    Args:
        Z: Linkage matrix from scipy.cluster.hierarchy.linkage
        structure_ids: List of structure IDs
        
    Returns:
        list: List of alignments to perform [(source1, target1), (source2, target2), ...]
    """
    # Build the guide tree
    tree, root_id = create_guide_tree(Z, structure_ids)
    
    # Get the visit order by traversing the tree
    node_order = traverse_tree(tree, root_id)
    
    # Build alignment pairs
    alignment_pairs = []
    visited_nodes = set()
    
    for node_id in node_order:
        node = tree[node_id]
        visited_nodes.add(node_id)
        
        if not node['is_leaf']:
            # For internal nodes, create alignment between children
            left, right = node['children']
            
            # Get actual structure IDs instead of node IDs for leaf nodes
            if tree[left]['is_leaf']:
                left_id = tree[left]['id']
            else:
                # For non-leaf, use a representative structure
                left_id = find_representative(tree, left, structure_ids)
                
            if tree[right]['is_leaf']:
                right_id = tree[right]['id']
            else:
                right_id = find_representative(tree, right, structure_ids)
                
            alignment_pairs.append((left_id, right_id))
    
    return alignment_pairs

def find_representative(tree, node_id, structure_ids):
    """
    Find a representative structure for a subtree.
    
    Args:
        tree: Guide tree 
        node_id: Node ID to find representative for
        structure_ids: List of structure IDs
        
    Returns:
        str: Representative structure ID
    """
    node = tree[node_id]
    
    # If it's a leaf node, return its structure ID
    if node['is_leaf']:
        return node['id']
    
    # For internal nodes, find a leaf by traversing the left branch
    current = node_id
    while not tree[current]['is_leaf']:
        current = tree[current]['children'][0]  # Use the left child
    
    return tree[current]['id']

def generate_transitive_alignment_paths(alignment_paths, structure_ids, alignment_pairs):
    """
    Generate transitive alignment paths based on the progressive alignment order.
    
    Args:
        alignment_paths: Dictionary with existing alignment paths between structure pairs
        structure_ids: List of structure IDs
        alignment_pairs: List of alignment pairs from create_alignment_order
        
    Returns:
        dict: Enhanced alignment_paths with transitive alignments
    """
    # Create a copy of the original alignment paths
    enhanced_paths = alignment_paths.copy()
    
    # Process each alignment pair from the tree
    for source_id, target_id in alignment_pairs:
        # Skip if direct alignment already exists
        if (source_id, target_id) in enhanced_paths or (target_id, source_id) in enhanced_paths:
            continue
        
        # Try to create a transitive alignment through intermediates
        found_path = False
        
        # Try to find a intermediate structure that connects source and target
        for intermediate in structure_ids:
            if intermediate == source_id or intermediate == target_id:
                continue
                
            # Check if we have paths from intermediate to both source and target
            path1_exists = (intermediate, source_id) in enhanced_paths or (source_id, intermediate) in enhanced_paths
            path2_exists = (intermediate, target_id) in enhanced_paths or (target_id, intermediate) in enhanced_paths
            
            if path1_exists and path2_exists:
                # Get the alignments, swapping if needed to get consistent direction
                if (intermediate, source_id) in enhanced_paths:
                    align1 = enhanced_paths[(intermediate, source_id)]
                    # Need to invert mapping for source->intermediate
                    residue_mapping1 = [(b, a) for a, b in align1['residue_mapping']]
                else:
                    align1 = enhanced_paths[(source_id, intermediate)]
                    residue_mapping1 = align1['residue_mapping']
                    
                if (intermediate, target_id) in enhanced_paths:
                    align2 = enhanced_paths[(intermediate, target_id)]
                    # Need to invert mapping for target->intermediate
                    residue_mapping2 = [(b, a) for a, b in align2['residue_mapping']]
                else:
                    align2 = enhanced_paths[(target_id, intermediate)]
                    residue_mapping2 = align2['residue_mapping']
                
                # Create a lookup for the second mapping
                mapping2_dict = {a: b for a, b in residue_mapping2}
                
                # Combine the mappings
                combined_mapping = []
                for source_res, inter_res in residue_mapping1:
                    if inter_res in mapping2_dict:
                        # Found a path from source to target via intermediate
                        target_res = mapping2_dict[inter_res]
                        combined_mapping.append((source_res, target_res))
                
                if combined_mapping:
                    # Calculate approximate RMSD for the transitive alignment
                    # (using the sum of the two component RMSDs as an approximation)
                    combined_rmsd = align1['rmsd'] + align2['rmsd']
                    
                    # Create a synthetic alignment path
                    enhanced_paths[(source_id, target_id)] = {
                        'rotation': None,  # No direct rotation/translation
                        'translation': None,
                        'residue_mapping': combined_mapping,
                        'rmsd': combined_rmsd,
                        'transitive': True,  # Mark as a transitive alignment
                        'via': intermediate  # Record the intermediate structure
                    }
                    
                    # Also create the reverse mapping
                    enhanced_paths[(target_id, source_id)] = {
                        'rotation': None,
                        'translation': None,
                        'residue_mapping': [(b, a) for a, b in combined_mapping],
                        'rmsd': combined_rmsd,
                        'transitive': True,
                        'via': intermediate
                    }
                    
                    found_path = True
                    break
        
        if not found_path:
            print(f"Warning: Could not create alignment path between {source_id} and {target_id}")
    
    return enhanced_paths

def create_tree_based_seq_alignment_dicts(rmsd_df, alignment_paths, method='average'):
    """
    Create sequence alignment dictionaries using the similarity tree approach.
    
    Args:
        rmsd_df: DataFrame with RMSD values
        alignment_paths: Dictionary with existing alignment paths
        method: Linkage method for tree construction
        
    Returns:
        dict: Sequence alignment dictionary format compatible with generate_grn_msa_tables
    """
    # Extract structure IDs from RMSD matrix
    structure_ids = rmsd_df.index.tolist()
    
    # Build the similarity tree
    Z, ordered_structure_ids = build_similarity_tree(rmsd_df, method=method)
    
    # Create alignment pairs from the tree
    alignment_pairs = create_alignment_order(Z, structure_ids)
    
    # Generate enhanced alignment paths with transitive mappings
    enhanced_paths = generate_transitive_alignment_paths(alignment_paths, structure_ids, alignment_pairs)
    
    # Select a central reference structure (structure with lowest sum of RMSD to all others)
    central_ref = find_central_reference(rmsd_df)
    
    # Generate group-specific references
    group_refs = {}
    
    # Initialize seq_alignment_dicts structure
    seq_alignment_dicts = {
        'global': {},
        'type': {}
    }
    
    # Process global alignments (all structures aligned to central reference)
    for struct_id in structure_ids:
        if struct_id == central_ref:
            continue  # Skip the reference itself
        
        # Check if alignment exists between central reference and this structure
        alignment_key = None
        if (central_ref, struct_id) in enhanced_paths:
            alignment_key = (central_ref, struct_id)
        elif (struct_id, central_ref) in enhanced_paths:
            alignment_key = (struct_id, central_ref)
            
        if alignment_key:
            alignment_data = enhanced_paths[alignment_key]
            
            # Extract residue mapping and normalize direction
            residue_mapping = alignment_data.get('residue_mapping', [])
            if alignment_key[0] != central_ref:
                # Swap the mapping to have reference first
                residue_mapping = [(b, a) for a, b in residue_mapping]
            
            # Create mapping dictionary
            mapping_dict = {}
            for ref_pos, aligned_pos in residue_mapping:
                mapping_dict[ref_pos] = aligned_pos
            
            # Add to global alignments
            seq_alignment_dicts['global'][struct_id] = mapping_dict
    
    # Return the alignment dictionaries
    return seq_alignment_dicts, central_ref, enhanced_paths

def find_central_reference(rmsd_df):
    """
    Find a central reference structure with the lowest sum of RMSD to all others.
    
    Args:
        rmsd_df: DataFrame with RMSD values
        
    Returns:
        str: ID of the central reference structure
    """
    # Calculate sum of RMSD for each structure to all others
    rmsd_sums = rmsd_df.sum()
    
    # Find structure with minimum sum
    central_ref = rmsd_sums.idxmin()
    
    return central_ref

def align_and_assign_grn_tree_based(data_dict, method='average'):
    """
    Wrapper function to create a tree-based alignment and prepare for GRN assignment.
    
    Args:
        data_dict: Dictionary with data from previous steps
        method: Linkage method for tree construction
        
    Returns:
        tuple: (seq_alignment_dicts, central_ref, enhanced_paths)
    """
    # Extract necessary data from data_dict
    processed_structures = data_dict['processed_structures']
    alignment_paths = data_dict['alignment_paths']
    rmsd_df = data_dict['rmsd_df']
    
    # Create tree-based sequence alignment
    seq_alignment_dicts, central_ref, enhanced_paths = create_tree_based_seq_alignment_dicts(
        rmsd_df, alignment_paths, method=method
    )
    
    return seq_alignment_dicts, central_ref, enhanced_paths